version: '3'

services:
  site:
    container_name: guide
    environment:
      JEKYLL_ENV: docker
    command: jekyll serve --watch --force_polling --config _config.docker.yml
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000